schema_version = "1.0.0"
id = "gauss_cannon"
version = "1.3.0"
name = "Gauss Cannon"
tagline = "Camera paths and point clouds for Gaussian Splatting workflows"
maintainer = "Warpgate Labs <contact@warp-gate.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/warpgatelabs/gauss-cannon"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Import-Export", "Render"]

blender_version_min = "5.0.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Write cameras and pointclouds to disk"